### ISSUE TITLE
Permission Denied Issues in Dockerized Cardano Node with Ratarmount Integration

### ISSUE THREAD

**Issue by Ishannaik** [mxmlnkn/ratarmount#147]
I am facing issues running a Dockerized Cardano Node where I'm integrating `ratarmount` to handle compressed immutable DB files. The container keeps crashing due to permission errors

1. **Docker Compose Configuration**:
   ```yaml
   services:
     cardano-node:
       image: ghcr.io/intersectmbo/cardano-node:10.1.4
       container_name: cardano-node
       restart: always
       ports:
         - "3001:3001"
         - "12798:12798"
       volumes:
         - ./config:/config
         - ./db:/db
         - ./scripts:/scripts
         - ./socket:/socket
       command: >
         run
         --topology /config/topology.json
         --database-path /db
         --socket-path /socket/node.socket
         --host-addr 0.0.0.0
         --port 3001
         --config /config/config.json
   ```

2. **Ratarmount Command Used**:
   ```bash
   ratarmount --write-overlay /home/pixashield/cardano-node/db/ratar/writeoverlay \
              /home/pixashield/cardano-node/db/ratar/archive/*.tar.xz \
              /home/pixashield/cardano-node/db/immutable
   ```

3. **Key Issues**:
   - Container restarts due to `FsInsufficientPermissions` for `/db/immutable`.

4. **Environment**:
   - Host: Debian
   - Docker
   - Ratarmount: Latest (via pip in a conda environment)

5. **Steps Tried**:
   - Ensured correct ownership (`chown -R 1000:1001 ./db`).
   - Verified execution permissions inside the container.
   - Enabled `privileged: true` for the container.
   - Mounted volumes with appropriate paths and permissions.

6. **Error Logs**:
   - On startup:
     ```
     FsInsufficientPermissions for /db/immutable: Permission denied
     ```

7. **Expected Behavior**:
   - The container should correctly access the mounted volumes and process the immutable DB files.

---

**Request**:  
- How can I properly configure `ratarmount` and Docker to avoid these permission issues?
- Are there known limitations with mounting volumes managed by `ratarmount` into Docker?

---
reference url: https://forum.cardano.org/t/proof-of-concept-compressed-chain-database/119263/
